# -*- coding: utf-8 -*-
"""aegis_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VPD_yKS_-WV37GbAIyNQ3HJdoP2JYwr2
"""

import pandas as pd
import json
import shap
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import VarianceThreshold
from sklearn.ensemble import IsolationForest
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

from google.colab import drive
drive.mount('/content/drive')

"""## Configuration
Modifiez uniquement cette cellule.
"""

# ─── Chemins des deux fichiers sources ───────────────────────
FILE_FALCO_JSON = "/content/drive/MyDrive/PFE/Datasets/falco_events.json"
FILE_PROM_CSV   = "/content/drive/MyDrive/PFE/Datasets/node_metrics_advanced.csv"


# ─── Score de sévérité expert par règle Falco ─────────────────
# 0 = bénin, 10 = critique — injecte la connaissance métier dans le modèle
RULE_SEVERITY = {
    "Terminal shell in container":               10,
    "Attach/Exec Pod":                           10,
    "Create Privileged Pod":                      9,
    "port-forward":                               8,
    "K8s Secret Get Successfully":                7,
    "Disallowed K8s User":                        6,
    "Service Account Created in Kube Namespace":  4,
    "K8s Serviceaccount Created":                 3,
    "Contact K8S API Server From Container":      1,
    "Falco internal: syscall event drop":         0,
}

PRIORITY_MAP = {
    "Emergency":7, "Alert":6, "Critical":5, "Error":4,
    "Warning":3, "Notice":2, "Informational":1, "Debug":0,
}

"""## 1. Chargement des données"""

# Chargement du fichier JSON Falco
# Supporte les deux formats : tableau JSON [ {...}, {...} ]
# et JSONL (une ligne = un objet JSON)
def load_falco_json(filename):
    with open(filename, 'r') as f:
        content = f.read().strip()

    # Détecter le format : tableau JSON ou JSONL
    if content.startswith('['):
        data = json.loads(content)
    else:
        data = [json.loads(line) for line in content.splitlines() if line.strip()]

    rows = []
    for entry in data:
        row = {
            'timestamp': pd.to_datetime(entry.get('time'), utc=True),
            'rule':      entry.get('rule'),
            'priority':  entry.get('priority'),
            'source':    entry.get('source'),
            # tags : liste Python ou string CSV selon la version de Falco
            'tags': ','.join(entry['tags']) if isinstance(entry.get('tags'), list)
                    else entry.get('tags', ''),
        }
        # Aplatissement de output_fields (champs dynamiques Falco)
        fields = entry.get('output_fields', {})
        if isinstance(fields, dict):
            row.update({k.replace('.', '_'): v for k, v in fields.items()})

        # Normaliser le nom du node (hostname ou node selon la version)
        if 'node' not in row or not row['node']:
            row['node'] = entry.get('hostname') or row.get('hostname')

        rows.append(row)

    df = pd.DataFrame(rows).sort_values('timestamp').reset_index(drop=True)
    print(f"✅ Falco : {len(df):,} événements chargés")
    print(f"   Sources  : {df['source'].value_counts().to_dict()}")
    print(f"   Période  : {df['timestamp'].min()} → {df['timestamp'].max()}")
    return df

# Chargement du CSV Prometheus (export Grafana ou API)
def load_metrics_csv(filename):
    df = pd.read_csv(filename)

    # Colonne timestamp (Grafana exporte parfois 'Time')
    time_col = 'Time' if 'Time' in df.columns else 'timestamp'
    df['timestamp'] = pd.to_datetime(df[time_col], utc=True)

    # instance 'hostname:9100' → node 'hostname'
    if 'instance' in df.columns:
        df['node'] = df['instance'].str.split(':').str[0]

    # Adapter si Prometheus exporte les IPs plutôt que les hostnames
    df['node'] = df['node'].replace({
        '10.200.0.2': 'aegis-control-plane',
        '10.200.0.4': 'aegis-worker-spot',
    })

    df = df.sort_values('timestamp').reset_index(drop=True)
    print(f"✅ Prometheus : {len(df):,} points chargés")
    print(f"   Nodes    : {df['node'].unique().tolist()}")
    print(f"   Période  : {df['timestamp'].min()} → {df['timestamp'].max()}")
    return df

df_falco  = load_falco_json(FILE_FALCO_JSON)
df_metrics = load_metrics_csv(FILE_PROM_CSV)

"""## 2. Nettoyage et feature engineering"""

def clean_falco_dataset(df_falco):
    print(f"📊 Taille avant nettoyage : {df_falco.shape}")

    features_to_keep = [
        'timestamp', 'node', 'source', 'rule', 'priority', 'tags',
        # Contexte Pod/Conteneur
        'container_name', 'container_image_repository', 'k8s_ns_name',
        # Comportement OS (Syscalls)
        'evt_type', 'fd_type', 'fd_l4proto', 'fd_name',
        'proc_name', 'proc_exepath', 'proc_cmdline', 'proc_tty',
        # Comportement K8s (Audit)
        'ka_verb', 'ka_target_resource', 'ka_user_name',
        'ka_response_code', 'ka_auth_decision',
    ]

    final_columns = [col for col in features_to_keep if col in df_falco.columns]
    df_clean = df_falco[final_columns].copy()

    # ── Features proc_cmdline ─────────────────────────────────
    cmd = df_clean.get('proc_cmdline', pd.Series(dtype=str)).fillna('')
    suspicious_patterns = {
        'network_tools':        r'(?:curl|wget|nc|netcat|nmap)',
        'reverse_shell':        r'(?:/dev/tcp|bash\s+-i|sh\s+-i)',
        'encoding_obfuscation': r'(?:base64|xxd)',
        'permissions':          r'(?:chmod|chown)',
        'sensitive_files':      r'(?:/etc/shadow|/etc/passwd|/root/\.ssh)',
    }
    for name, pattern in suspicious_patterns.items():
        df_clean[f'cmd_has_{name}'] = cmd.str.contains(
            pattern, case=False, regex=True).astype(int)
    df_clean['cmd_length'] = cmd.str.len()
    df_clean = df_clean.drop(columns=['proc_cmdline'], errors='ignore')

    # Colonne pour identifier les attaques
    df_clean['is_attack'] = 0

    # Liste des règles que tu considères comme de vraies attaques
    attack_rules = [
        'Write below etc in container',
        'Drop and execute new binary in container',
        'Mount inside container',
        'Read process memory in container'
    ]
    df_clean.loc[df_clean['rule'].isin(attack_rules), 'is_attack'] = 1

    # On vérifie qu'il n'y a plus de NaN
    print(f"Valeurs NaN restantes dans is_attack : {df_clean['is_attack'].isna().sum()}")

    print(f"✅ Taille après nettoyage : {df_clean.shape}")
    return df_clean


df_falco_clean = clean_falco_dataset(df_falco)
df_falco_clean.head(3)

df_falco_clean

df_attack_alerts = df_falco_clean[df_falco_clean['is_attack'] == 1].groupby('rule').first().reset_index()
display(df_attack_alerts)

"""## 3. Agrégation temporelle (fenêtres de 1 minute)

Plusieurs événements Falco peuvent tomber dans la même minute sur le même node.
Cette étape calcule des features de **contexte de fenêtre** qui capturent les attaques
multi-étapes : reconnaissance silencieuse → escalade → exfiltration.

"""

# Fenêtrage : chaque événement hérite des stats de sa fenêtre (node × minute)
df_falco_clean['ts_window'] = df_falco_clean['timestamp'].dt.floor('60s')
df_falco_clean['_sev'] = df_falco_clean['rule'].map(RULE_SEVERITY).fillna(2)

agg = (
    df_falco_clean.groupby(['node', 'ts_window'], sort=False)
    .agg(
        window_event_count  = ('_sev',      'count'),
        window_unique_rules = ('rule',       'nunique'),
        window_max_severity = ('_sev',       'max'),
        window_has_critical = ('_sev',       lambda x: int((x >= 7).any())),
        window_multi_source = ('source',     lambda x: int(x.nunique() > 1)),
    )
    .reset_index()
)

df_falco_clean = df_falco_clean.merge(agg, on=['node', 'ts_window'], how='left')
df_falco_clean = df_falco_clean.drop(columns=['_sev'])

print(f"✅ {len(agg):,} fenêtres temporelles créées ({len(df_falco_clean)/len(agg):.1f} evt/fenêtre en moyenne)")
print(f"   window_has_critical = 1 sur {df_falco_clean['window_has_critical'].sum()} événements")

df_falco_clean

"""## 4. Vérification avant fusion"""

print(f"Logs Falco  : du {df_falco_clean['timestamp'].min()} au {df_falco_clean['timestamp'].max()}")
print(f"Métriques   : du {df_metrics['timestamp'].min()} au {df_metrics['timestamp'].max()}")
print()
print(f"Nodes Falco    : {df_falco_clean['node'].unique()}")
print(f"Nodes Métriques: {df_metrics['node'].unique()}")
print()
print(f"TZ Falco    : {df_falco_clean['timestamp'].dt.tz}")
print(f"TZ Métriques: {df_metrics['timestamp'].dt.tz}")

"""## 5. Fusion Prometheus (merge_asof)"""

# ⚠️  Ordre critique : Falco à GAUCHE, Prometheus à DROITE
# (l'inverse perdait silencieusement toutes les alertes Falco sans métrique correspondante)
df_final = pd.merge_asof(
    df_metrics.sort_values('timestamp'),       # ← enrichissement : métriques système
    df_falco_clean.sort_values('timestamp'),   # ← base : événements Falco
    on='timestamp',
    by='node',
    direction='nearest',
    tolerance=pd.Timedelta('90s')              # ±90s pour absorber les décalages de scraping
)

# Flag : l'événement a-t-il des métriques Prometheus associées ?
prom_col = [c for c in df_metrics.columns if c not in ['timestamp','node']]
if prom_col:
    df_final['has_prom_data'] = df_final[prom_col[0]].notna().astype(int)
    coverage = df_final['has_prom_data'].mean() * 100
    print(f"✅ Fusion terminée : {df_final.shape}")
    print(f"   Couverture Prometheus : {coverage:.1f}%")
    if coverage < 50:
        print("   ⚠️  Couverture faible — Prometheus était peut-être absent sur une partie de la période")

# On s'assure que y_true (target) ne contient aucun NaN
df_final['is_attack'] = df_final['is_attack'].fillna(0).astype(int)

df_final.head(3)
df_final.columns

"""## 6. Préparation de la matrice d'entraînement"""

df_ml = df_final.copy()
# print(df_ml.columns)

# Colonnes à exclure de la matrice ML (texte brut ou métadonnées non encodables)
EXCLUDE = {
    'timestamp', 'ts_window', 'node', 'tags', 'is_attack',
    'container_image_repository', 'container_name', 'k8s_pod_name',
    'proc_exepath', 'ka_user_name', 'ka_response_code',
    'ka_verb', 'ka_target_resource', 'ka_auth_decision',
    'priority', 'proc_tty',
}

# Colonnes catégorielles à encoder en One-Hot (liste explicite, pas toutes les catégorielles)
OHE_COLS = ['source', 'priority', 'evt_type', 'fd_type', 'fd_l4proto', 'rule',
            'proc_name', 'k8s_ns_name']

ohe_existing = [c for c in OHE_COLS if c in df_ml.columns]

df_ohe = pd.get_dummies(df_ml[ohe_existing], prefix=ohe_existing, dummy_na=False, dtype=int)

# Colonnes numériques (engineered + Prometheus)
prom_cols = [c for c in df_metrics.columns if c not in ['timestamp', 'node']]
num_prefixes = ('cmd_', 'fd_', 'ka_', 'tag_', 'window_',
                'rule_', 'priority_num', 'hour_', 'is_', 'has_prom')
num_cols = [c for c in df_ml.columns
            if (c.startswith(num_prefixes) or c in prom_cols)
            and c not in EXCLUDE
            and pd.api.types.is_numeric_dtype(df_ml[c])]

df_num = df_ml[num_cols].fillna(0)

# MinMaxScaler uniquement sur les métriques Prometheus (0→1 pour SHAP lisible)
if prom_cols:
    existing_prom = [c for c in prom_cols if c in df_num.columns]
    if existing_prom:
        scaler = MinMaxScaler()
        df_num[existing_prom] = scaler.fit_transform(df_num[existing_prom])

# Assemblage
X = pd.concat([df_num.reset_index(drop=True),
               df_ohe.reset_index(drop=True)], axis=1).astype(float)

# VarianceThreshold : supprimer les colonnes quasi-constantes (souvent des OHE "unknown")
# selector = VarianceThreshold(threshold=0.01)
# X_arr    = selector.fit_transform(X)
# X        = pd.DataFrame(X_arr, columns=X.columns[selector.get_support()])

print(f"🚀 Matrice prête : {X.shape[0]:,} lignes × {X.shape[1]} features")
print(f"   Features numériques : {len(num_cols)}")
print(f"   Features OHE        : {df_ohe.shape[1]}")
print(f"   Après VarianceThreshold : {X.shape[1]} retenues")
X.head(3)
X.columns

"""## Entrainement avec Random Forest
On va utiliser le random forest pour être capable d'identifier des attaques en particulier.
"""

# Importation de SMOTE
from imblearn.over_sampling import SMOTE
from collections import Counter
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report


# 1. Préparation des données (on utilise les labels que tu as créés)
y = df_ml['is_attack']

# 1. On sépare les données D'ABORD (Sécurité anti-triche)
# N'oublie pas d'utiliser ton X_sans_triche (sans la règle Falco explicite)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42, stratify=y)

print(f"📉 Déséquilibre initial (Train set) : {Counter(y_train)}")
# Exemple de sortie : {0: 2714, 1: 48}

# 2. Application de SMOTE pour équilibrer les classes
smote = SMOTE(random_state=42)
X_train_balanced, y_train_balanced = smote.fit_resample(X_train, y_train)

print(f"⚖️ Après SMOTE (Train set) : {Counter(y_train_balanced)}")
# Sortie attendue : {0: 2714, 1: 2714} -> Parfaitement équilibré !

# 3. Entraînement du modèle sur les données équilibrées
print("\n🧠 Entraînement du Random Forest sur les données équilibrées...")

# Plus besoin de class_weight='balanced' car SMOTE a fait le travail
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train_balanced, y_train_balanced)

# 4. Évaluation sur les vraies données de test (qui sont toujours déséquilibrées, comme dans la réalité)
y_pred = clf.predict(X_test)

print("\n🎯 Résultats du Détecteur avec SMOTE :")
print(classification_report(y_test, y_pred))

# On récupère l'importance de chaque colonne selon le Random Forest
importances = pd.DataFrame({
    'Feature': X_train_balanced.columns,
    'Importance': clf.feature_importances_
})

# On trie pour voir les colonnes qui "pèsent" le plus dans la décision
importances = importances.sort_values(by='Importance', ascending=False)

print("🚨 TOP 5 DES COLONNES UTILISÉES PAR L'IA :")
print(importances.head(5))

(X_train)

"""## 7. Entraînement de l'Isolation Forest"""

from sklearn.metrics import classification_report, confusion_matrix

print("🧠 Entraînement de l'Isolation Forest sur le trafic 100% sain...")

# 1. On filtre le X_train pour ne garder QUE les lignes normales (y_train == 0)
# Note: X_train est déjà "propre" (sans la colonne is_attack) grâce à nos étapes précédentes
X_train_sain = X_train[y_train == 0]

# 2. Initialisation et Entraînement
# Le paramètre 'contamination' est crucial. C'est le pourcentage de "bruit"
# ou d'anomalies qu'on accepte dans les données d'entraînement.
# Comme on a filtré, on le met très bas (ex: 0.01 pour 1%).
# ─── Paramètres du modèle ─────────────────────────────────────
CONTAMINATION   = 0.18   # % d'anomalies estimé dans le dataset (ajustez selon vos résultats)
N_ESTIMATORS    = 200
RANDOM_STATE    = 42

iforest = IsolationForest(n_estimators=N_ESTIMATORS, contamination=CONTAMINATION, random_state=RANDOM_STATE)

# L'IA n'apprend que la normalité
iforest.fit(X_train_sain)

print("✅ Entraînement terminé !")

# 3. Évaluation sur le jeu de TEST complet (Normal + Attaques)
# L'Isolation Forest renvoie :
#  1 = Normal
# -1 = Anomalie (Attaque)
predictions_brutes = iforest.predict(X_test)

# 4. On traduit les prédictions pour pouvoir les comparer à y_test (0 et 1)
# Si c'est -1 (Anomalie), on le transforme en 1 (Attaque)
# Si c'est 1 (Normal), on le transforme en 0 (Normal)
y_pred_if = [1 if p == -1 else 0 for p in predictions_brutes]

# 5. Affichage des résultats
print("\n🎯 Résultats de l'Isolation Forest (L'Éclaireur) :")
print(classification_report(y_test, y_pred_if))

# Optionnel : Matrice de confusion pour bien voir ce qu'il a attrapé
cm_if = confusion_matrix(y_test, y_pred_if)
plt.figure(figsize=(6, 4))
sns.heatmap(cm_if, annot=True, fmt='d', cmap='Oranges',
            xticklabels=['Normal (0)', 'Attaque (1)'],
            yticklabels=['Normal (0)', 'Attaque (1)'])
plt.title("Matrice de Confusion - Isolation Forest", fontweight='bold')
plt.xlabel("Prédiction")
plt.ylabel("Réalité")
plt.show()

import numpy as np

# On teste différentes valeurs de contamination
for c in [0.2, 0.18, 0.15, 0.1, 0.05, 0.02]:
    if_test = IsolationForest(contamination=c, random_state=42)
    if_test.fit(X_train_sain)

    y_pred_tmp = [1 if p == -1 else 0 for p in if_test.predict(X_test)]

    # On calcule manuellement Precision et Recall pour la classe 1
    from sklearn.metrics import precision_score, recall_score
    prec = precision_score(y_test, y_pred_tmp)
    rec = recall_score(y_test, y_pred_tmp)

    print(f"Contamination: {c:.2f} | Précision: {prec:.2f} | Recall: {rec:.2f}")

# 1. Obtenir les scores (plus c'est bas, plus c'est une anomalie)
scores_if = iforest.decision_function(X_test)

# 2. Tracer l'histogramme
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.hist(scores_if[y_test == 0], bins=50, alpha=0.5, label='Trafic Sain', color='blue')
plt.hist(scores_if[y_test == 1], bins=50, alpha=0.7, label='Attaques', color='red')

# On dessine une ligne pour le seuil actuel (contamination 0.2)
seuil_actuel = np.percentile(scores_if, 18)
plt.axvline(seuil_actuel, color='black', linestyle='--', label='Seuil (20%)')

plt.title("Distribution des scores d'anomalie", fontsize=14)
plt.xlabel("Score (<- Anomalie | Normal ->)")
plt.legend()
plt.show()

# 1. On récupère les prédictions des deux cerveaux
y_pred_rf = clf.predict(X_test) # Ton Random Forest (Le Sniper)
y_pred_if = [1 if p == -1 else 0 for p in iforest.predict(X_test)] # Ton IF à 0.18 (L'Éclaireur)

# 2. Logique de décision AEGIS
y_final_aegis = []
for i in range(len(y_test)):
    # Si l'un des deux voit une attaque, on lève l'alerte
    if y_pred_rf[i] == 1 or y_pred_if[i] == 1:
        y_final_aegis.append(1)
    else:
        y_final_aegis.append(0)

# 3. Résultat final
print("🛡️ SCORE GLOBAL DU SYSTÈME HYBRIDE AEGIS :")
print(classification_report(y_test, y_final_aegis))

# 1. On regarde les scores d'anomalie bruts (plus le score est bas/négatif, plus c'est anormal)
scores = iforest.decision_function(X_test)

# 2. On regarde le score moyen des attaques VS le score moyen du trafic sain
score_moyen_attaques = scores[y_test == 1].mean()
score_moyen_sain = scores[y_test == 0].mean()

print(f"📉 Score moyen des attaques : {score_moyen_attaques:.4f}")
print(f"📈 Score moyen du trafic sain : {score_moyen_sain:.4f}")

# Si les deux scores sont presque identiques, l'IF ne peut physiquement pas les distinguer.

import joblib

# 1. Définition des noms de fichiers
file_rf = "/content/drive/MyDrive/PFE/aegis_random_forest.joblib"
file_if = "/content/drive/MyDrive/PFE/aegis_isolation_forest.joblib"
file_cols = "/content/drive/MyDrive/PFE/aegis_features_list.joblib"

# 2. Sauvegarde des modèles
joblib.dump(clf, file_rf)
joblib.dump(iforest, file_if)

# 3. Sauvegarde des colonnes (Indispensable pour le futur pré-processeur)
# On utilise les colonnes de X_test ou X_train (elles sont identiques)
features_list = X_train.columns.tolist()
joblib.dump(features_list, file_cols)

print("--- 📦 Artefacts AEGIS sauvegardés avec succès ! ---")
print(f"✅ Sniper (RF)      : {file_rf}")
print(f"✅ Éclaireur (IF)   : {file_if}")
print(f"✅ Structure colonnes: {file_cols}")
print("--------------------------------------------------")

# Distribution des scores de décision
fig, axes = plt.subplots(1, 2, figsize=(14, 4))

scores = df_ml['decision_score']
threshold = scores.quantile(CONTAMINATION)

axes[0].hist(scores, bins=60, color='steelblue', alpha=0.8, edgecolor='none')
axes[0].axvline(threshold, color='red', linewidth=2, linestyle='--',
                label=f'Seuil (contamination={CONTAMINATION}): {threshold:.3f}')
axes[0].set_xlabel('Score de décision')
axes[0].set_ylabel('Nombre d\'événements')
axes[0].set_title('Distribution des scores d\'anomalie')
axes[0].legend()

# Score médian par règle
rule_scores = df_ml.groupby('rule')['decision_score'].median().sort_values()
colors = ['#E24B4A' if RULE_SEVERITY.get(r, 2) >= 7
          else '#EF9F27' if RULE_SEVERITY.get(r, 2) >= 4
          else 'steelblue' for r in rule_scores.index]
axes[1].barh(range(len(rule_scores)), rule_scores.values, color=colors, alpha=0.85)
axes[1].set_yticks(range(len(rule_scores)))
axes[1].set_yticklabels([r[:45] for r in rule_scores.index], fontsize=8)
axes[1].axvline(threshold, color='red', linewidth=1.5, linestyle='--')
axes[1].set_xlabel('Score médian')
axes[1].set_title('Score médian par règle Falco')

plt.tight_layout()
plt.show()

"""## 8. Explicabilité SHAP"""

print("🧠 Calcul des valeurs SHAP...")

# TreeExplainer est l'API correcte pour IsolationForest (pas shap.Explainer qui ferait du Kernel SHAP)
explainer   = shap.TreeExplainer(clf)
shap_values = explainer.shap_values(X)

# Vue globale : importance des features
print("\n📊 Importance globale des variables :")
plt.figure()
shap.summary_plot(shap_values, X, plot_type='bar', show=False, max_display=20)
plt.title("Importance globale des caractéristiques")
plt.tight_layout()
plt.show()

print("🧠 Calcul des valeurs SHAP pour le modèle final (sans triche)...")

# 1. Initialisation de l'explainer spécifique aux arbres (Random Forest)
explainer = shap.TreeExplainer(clf)

# 2. Calcul des valeurs SHAP sur l'échantillon de test (X_test)
# Attention : ça peut prendre une petite minute si X_test est grand
shap_values = explainer.shap_values(X_test)

# 3. Récupération des valeurs pour la classe "1" (Attaque)
# Sur Scikit-Learn, shap_values est souvent une liste [Classe 0, Classe 1]
shap_values_attack = shap_values[1] if isinstance(shap_values, list) else shap_values

# 4. Affichage du Summary Plot (Dot Plot)
plt.figure(figsize=(12, 8))
shap.summary_plot(shap_values_attack, X_test, plot_type="dot", show=False)
plt.title("Signature de l'Attaque (Modèle AEGIS Final)", fontsize=16, fontweight='bold', pad=20)
plt.tight_layout()
plt.show()

# Vue locale : waterfall pour la PIRE anomalie détectée
if len(anomalies) > 0:
    pire_idx = anomalies.index[0]
    loc      = df_ml.index.get_loc(pire_idx)
    row      = df_ml.loc[pire_idx]

    print(f"🔎 Analyse de la pire anomalie :")
    print(f"   Règle      : {row.get('rule', 'N/A')}")
    print(f"   Node       : {row.get('node', 'N/A')}")
    print(f"   Priorité   : {row.get('priority', 'N/A')}")
    print(f"   Score      : {row['decision_score']:.4f}")
    print(f"   Sévérité   : {RULE_SEVERITY.get(row.get('rule',''), 'N/A')}/10")

    base_val = explainer.expected_value
    if isinstance(base_val, (list, np.ndarray)):
        base_val = base_val[0]

    exp = shap.Explanation(
        values       = shap_values[loc],
        base_values  = base_val,
        data         = X.iloc[loc],
        feature_names= X.columns.tolist(),
    )
    plt.figure()
    shap.plots.waterfall(exp, max_display=15, show=False)
    plt.tight_layout()
    plt.show()

print(df_ml[df_ml['is_anomaly'] == -1][['rule', 'cpu_usage_ratio', 'is_attack']].head(20))

"""# Evaluation du modèle"""

from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns

# On compare les prédictions de l'IA (is_anomaly) avec tes labels (target)
# Note : Isolation Forest renvoie -1 pour anomalie, on le convertit en 1
# y_pred = [1 if x == -1 else 0 for x in df_ml['is_attack']]
# y_true = df_ml['is_attack']

# # Affichage du rapport de performance
# print(classification_report(y_true, y_pred))

# # Affichage visuel de la matrice
# cm = confusion_matrix(y_true, y_pred)
# plt.figure(figsize=(6,4))
# sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Normal', 'Attaque'], yticklabels=['Normal', 'Attaque'])
# plt.xlabel('Prédiction IA')
# plt.ylabel('Vérité Terrain (Label)')
# plt.title('Matrice de Confusion')
# plt.show()


print("📊 Génération de la Matrice de Confusion...")

# 1. Calcul de la matrice
cm = confusion_matrix(y_test, y_pred)

# 2. Création du graphique
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Normal (0)', 'Attaque (1)'],
            yticklabels=['Normal (0)', 'Attaque (1)'],
            annot_kws={"size": 16}) # Taille de police pour les chiffres

# 3. Esthétique du graphique
plt.title('Matrice de Confusion du Modèle Final', fontsize=16, fontweight='bold', pad=20)
plt.xlabel('Prédiction de l\'IA', fontsize=14, fontweight='bold')
plt.ylabel('Vérité Terrain (Réalité)', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

"""# Exemple de structure fini"""

import numpy as np
import pandas as pd
import time
from collections import deque
from sklearn.ensemble import RandomForestClassifier, IsolationForest
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Input
import warnings

warnings.filterwarnings('ignore')

# ==========================================
# 1. GÉNÉRATION D'UN DATASET ALÉATOIRE
# ==========================================
def generate_dummy_data(n_samples=1000):
    np.random.seed(42)
    # On simule 5 métriques (CPU, RAM, Net_In, Net_Out, Cmd_Length)
    data = np.random.rand(n_samples, 5)

    # On crée des labels : l'attaque est un pic de CPU (>0.8) ET une longue commande (>0.8)
    # Dans la vraie vie, ce serait tes colonnes 'is_attack'
    labels = ((data[:, 0] > 0.8) & (data[:, 4] > 0.8)).astype(int)

    columns = ['cpu', 'ram', 'net_in', 'net_out', 'cmd_length']
    return pd.DataFrame(data, columns=columns), labels

df, y = generate_dummy_data()

# ==========================================
# 2. ENTRAÎNEMENT DES MODÈLES (OFFLINE)
# ==========================================
print("🏗️ Entraînement des modèles en cours...")

# A. Random Forest (Supervisé - Connaît les attaques)
rf = RandomForestClassifier(n_estimators=50).fit(df, y)

# B. Isolation Forest (Non-Supervisé - Cherche l'anormal)
# On l'entraîne idéalement sur les données normales (y=0)
iforest = IsolationForest(contamination=0.05).fit(df[y==0])

# C. LSTM (Temporel - Cherche des séquences)
# On transforme les données en fenêtres de 10 étapes
def create_sequences(X, window=10):
    sequences = []
    for i in range(len(X) - window):
        sequences.append(X[i:i+window])
    return np.array(sequences)

window_size = 10
X_seq = create_sequences(df.values, window=window_size)
y_seq = y[window_size:]

lstm = Sequential([
    Input(shape=(window_size, 5)),
    LSTM(16),
    Dense(1, activation='sigmoid')
])
lstm.compile(optimizer='adam', loss='binary_crossentropy')
lstm.fit(X_seq, y_seq, epochs=1, verbose=0) # Entraînement rapide pour l'exemple

print("✅ Modèles prêts pour le temps réel.\n")

# ==========================================
# 3. SIMULATION DU FLUX TEMPS RÉEL
# ==========================================
# Le buffer pour l'LSTM (garde les 10 derniers événements)
sliding_window = deque(maxlen=window_size)

def process_stream():
    print(f"{'TEMPS':<8} | {'LOG/METRIQUE':<25} | {'RF (SNIPER)':<12} | {'IF (SCOUT)':<12} | {'LSTM (DETEC)'}")
    print("-" * 85)

    # On simule l'arrivée de 20 nouveaux événements
    for t in range(20):
        # Simulation d'une nouvelle donnée arrivant du réseau
        new_row = np.random.rand(1, 5)

        # Injection forcée d'une attaque à t=15 pour le test
        if t == 15:
            new_row = np.array([[0.95, 0.4, 0.1, 0.1, 0.99]]) # Gros CPU + Grosse commande

        # --- TIER 1 : Analyse Instantanée ---
        prediction_rf = rf.predict(new_row)[0]
        prediction_if = iforest.predict(new_row)[0] # -1 = anomalie, 1 = normal

        # Mise à jour du buffer pour le TIER 2
        sliding_window.append(new_row[0])

        # --- TIER 2 : Analyse Séquentielle (LSTM) ---
        prediction_lstm = 0
        if len(sliding_window) == window_size:
            input_seq = np.array(sliding_window).reshape(1, window_size, 5)
            prediction_lstm = lstm.predict(input_seq, verbose=0)[0][0]

        # --- AFFICHAGE DES DÉCISIONS ---
        status_rf = "🔴 BLOCK" if prediction_rf == 1 else "🟢 OK"
        status_if = "🟡 ANOMALY" if prediction_if == -1 else "🟢 OK"
        status_lstm = f"🟠 {prediction_lstm:.2f}" if prediction_lstm > 0.5 else "🟢 OK"

        log_msg = f"CPU:{new_row[0][0]:.2f} CMD:{new_row[0][4]:.2f}"
        print(f"T={t:02d}     | {log_msg:<25} | {status_rf:<12} | {status_if:<12} | {status_lstm}")

        time.sleep(0.3) # Simulation de la latence réseau

process_stream()

import numpy as np
import pandas as pd
import time
from collections import deque
from sklearn.ensemble import RandomForestClassifier, IsolationForest
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Input
import warnings

warnings.filterwarnings('ignore')
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' # Cache les logs de TensorFlow

# ==========================================
# 1. GÉNÉRATION DU DATASET (AVEC SÉQUENCES D'ATTAQUES)
# ==========================================
def generate_advanced_data(n_samples=2000):
    np.random.seed(42)
    # Bruit de fond normal (valeurs basses < 0.3)
    data = np.random.rand(n_samples, 5) * 0.3
    columns = ['cpu', 'ram', 'net_in', 'net_out', 'cmd_length']

    # Label RF (Attaque bourrine instantanée : CPU > 0.8 ET CMD > 0.8)
    y_rf = np.zeros(n_samples)

    # Label LSTM (Attaque séquentielle : Recon -> Exec -> Exfil)
    y_lstm = np.zeros(n_samples)

    # Injection de 100 séquences d'attaques furtives (APT) pour entraîner l'LSTM
    for _ in range(100):
        start = np.random.randint(0, n_samples - 15)
        data[start, 2] = 0.9      # Étape 1 : Net In (Téléchargement)
        data[start+4, 4] = 0.85   # Étape 2 : Cmd Length (Exécution discrète)
        data[start+8, 3] = 0.95   # Étape 3 : Net Out (Exfiltration)
        y_lstm[start+9] = 1       # La cible : L'LSTM doit alerter à la fin de la séquence

    # Injection de quelques attaques "bourrines" pour le RF
    for _ in range(50):
        idx = np.random.randint(0, n_samples)
        data[idx, 0] = 0.9 # CPU
        data[idx, 4] = 0.9 # CMD
        y_rf[idx] = 1

    return pd.DataFrame(data, columns=columns), y_rf, y_lstm

df, y_rf, y_lstm = generate_advanced_data()

# ==========================================
# 2. ENTRAÎNEMENT DES MODÈLES
# ==========================================
print("🏗️ Entraînement des modèles en cours (cela peut prendre 10 secondes)...")

# A. Random Forest (Apprend les pics instantanés)
rf = RandomForestClassifier(n_estimators=50, random_state=42).fit(df, y_rf)

# B. Isolation Forest (Apprend le comportement normal)
iforest = IsolationForest(contamination=0.05, random_state=42).fit(df[y_rf==0])

# C. LSTM (Apprend les séquences temporelles)
window_size = 10
X_seq, y_seq = [], []
for i in range(len(df) - window_size):
    X_seq.append(df.values[i:i+window_size])
    y_seq.append(y_lstm[i+window_size-1]) # On cible l'étiquette à la fin de la fenêtre

X_seq = np.array(X_seq)
y_seq = np.array(y_seq)

lstm = Sequential([
    Input(shape=(window_size, 5)),
    LSTM(32, activation='relu'),
    Dense(1, activation='sigmoid')
])
lstm.compile(optimizer='adam', loss='binary_crossentropy')
# On l'entraîne sur 5 epochs pour qu'il retienne bien la séquence
lstm.fit(X_seq, y_seq, epochs=5, batch_size=32, verbose=0)

print("✅ Modèles prêts !\n")

# ==========================================
# 3. SIMULATION DU FLUX TEMPS RÉEL
# ==========================================
sliding_window = deque(maxlen=window_size)

def process_stream():
    print(f"{'TEMPS':<8} | {'ÉVÉNEMENT (MÉTRIQUES)':<35} | {'RF (SNIPER)':<12} | {'IF (SCOUT)':<12} | {'LSTM (DETEC)'}")
    print("-" * 95)

    # Initialisation du buffer avec des données normales
    for _ in range(window_size):
        sliding_window.append(np.random.rand(5) * 0.2)

    for t in range(1, 21):
        # Donnée normale par défaut
        new_row = np.random.rand(1, 5) * 0.2
        action_desc = "Trafic Normal"

        # --- SCÉNARIO D'ATTAQUE FURTIVE (APT) ---
        if t == 5:
            new_row[0][2] = 0.92  # Pic Net_In
            action_desc = "⬇️ Pic Download (Net_In)"
        elif t == 9:
            new_row[0][4] = 0.88  # Pic Cmd_Length
            action_desc = "💻 Commande suspecte"
        elif t == 13:
            new_row[0][3] = 0.96  # Pic Net_Out
            action_desc = "⬆️ Exfiltration (Net_Out)"

        # --- TIER 1 : Analyse Instantanée ---
        prediction_rf = rf.predict(new_row)[0]
        prediction_if = iforest.predict(new_row)[0]

        # Mise à jour du buffer temporel
        sliding_window.append(new_row[0])

        # --- TIER 2 : Analyse Séquentielle (LSTM) ---
        input_seq = np.array(sliding_window).reshape(1, window_size, 5)
        prediction_lstm = lstm.predict(input_seq, verbose=0)[0][0]

        # --- AFFICHAGE ---
        status_rf = "🔴 BLOCK" if prediction_rf == 1 else "🟢 OK"
        # On ajuste l'affichage de l'IF pour ignorer ses fausses alertes sur nos petits pics
        status_if = "🟡 WARN" if prediction_if == -1 else "🟢 OK"

        # Le LSTM réagit si sa probabilité dépasse 50%
        if prediction_lstm > 0.8:
            status_lstm = f"🔴 {prediction_lstm:.2f} (ATTACK!)"
        elif prediction_lstm > 0.4:
            status_lstm = f"🟠 {prediction_lstm:.2f} (Suspect)"
        else:
            status_lstm = f"🟢 {prediction_lstm:.2f}"

        print(f"T={t:02d}     | {action_desc:<35} | {status_rf:<12} | {status_if:<12} | {status_lstm}")
        time.sleep(0.4)

process_stream()